# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrcPWHHU7MKJwTS2tWTE8TjPniOQzAMR
"""

import os
import numpy as np
import soundfile as sf

from scipy.signal import butter, sosfilt, resample
from numpy.fft import rfft, rfftfreq

INPUT_WAV = "/content/dis1.wav" #файл для последующей обработки
OUTPUT_DIR = "output_noise"

SNR_DB = 2

# файлы для многоголосого шума
BABBLE_FILES = [
    "babble1.wav",
    "babble2.wav",
    "babble3.wav",
    "babble4.wav",
    "babble5.wav",
    "babble6.wav",
    "babble7.wav",
    "babble8.wav",
    "babble9.wav",
    "babble10.wav",
    "babble11.wav",

]

os.makedirs(OUTPUT_DIR, exist_ok=True)

def rms(x):
    return np.sqrt(np.mean(x**2) + 1e-8)

def normalize_noise(signal, noise, snr_db):

    signal_rms = rms(signal)
    noise_rms = rms(noise)

    target_noise_rms = signal_rms / (10 ** (snr_db / 20))

    noise = noise * (target_noise_rms / noise_rms)

    return np.clip(signal + noise, -1.0, 1.0)

# розовый шум

def generate_pink_noise(n):

    n_cols = 16

    array = np.full((n, n_cols), np.nan)

    array[0, :] = np.random.random(n_cols)
    array[:, 0] = np.random.random(n)

    cols = np.random.geometric(0.5, n)
    cols = np.clip(cols, 1, n_cols) - 1

    for i in range(1, n):

        array[i] = array[i - 1]
        array[i, cols[i - 1]] = np.random.random()

    pink = np.nansum(array, axis=1)

    pink -= np.mean(pink)
    pink /= np.max(np.abs(pink))

    return pink


def add_pink_noise(signal, snr_db):

    noise = generate_pink_noise(len(signal))

    return normalize_noise(signal, noise, snr_db)

#многополосный белый шум
def bandpass_sos(low, high, sr, order=6):

    nyq = sr / 2

    return butter(
        order,
        [low / nyq, high / nyq],
        btype='band',
        output='sos'
    )


def get_band_power(signal, sr, low, high):

    freqs = rfftfreq(len(signal), 1 / sr)

    spectrum = np.abs(rfft(signal)) ** 2

    mask = (freqs >= low) & (freqs < high)

    return np.sqrt(np.mean(spectrum[mask]) + 1e-8)


def add_multiband_white_noise(signal, sr, snr_db):

    duration = len(signal)

    bands = [

        (80,   300,  1.5),   # F0
        (300,  700,  2.0),   # F1
        (700,  1200, 2.5),   # F2
        (2000, 3500, 2.0),   # F3
        (3500, 8000, 1.2),   # фрикативы
    ]

    noise = np.zeros(duration)

    for low, high, weight in bands:

        if high >= sr / 2:
            high = sr / 2 - 1

        band_power = get_band_power(
            signal,
            sr,
            low,
            high
        )

        white = np.random.randn(duration)

        sos = bandpass_sos(
            low,
            high,
            sr
        )

        band_noise = sosfilt(sos, white)

        noise += weight * band_power * band_noise

    return normalize_noise(signal, noise, snr_db)

# многоголосый шум

def generate_babble(target_length, sr, files):

    babble = np.zeros(target_length)

    for path in files:

        s, file_sr = sf.read(path)

        if s.ndim > 1:
            s = s.mean(axis=1)

        if file_sr != sr:

            s = resample(
                s,
                int(len(s) * sr / file_sr)
            )

        s /= rms(s)

        if len(s) < target_length:

            offset = np.random.randint(
                0,
                target_length - len(s)
            )

            babble[offset:offset + len(s)] += s

        else:

            start = np.random.randint(
                0,
                len(s) - target_length
            )

            babble += s[start:start + target_length]

    babble -= np.mean(babble)
    babble /= np.max(np.abs(babble))

    return babble


def add_babble_noise(signal, sr, snr_db):

    babble = generate_babble(
        len(signal),
        sr,
        BABBLE_FILES
    )

    return normalize_noise(signal, babble, snr_db)

# выпадение сигнала

def add_dropouts(signal, sr):

    out = signal.copy()

    step = int(sr * 0.1)
    width = int(sr * 0.05)

    for i in range(0, len(signal), step):

        attenuation = np.random.uniform(0.2, 0.8)

        out[i:i + width] *= attenuation

    return out

# загрузка аудио

signal, sr = sf.read(INPUT_WAV)

if signal.ndim > 1:
    signal = signal.mean(axis=1)




pink = add_pink_noise(
    signal,
    SNR_DB
)

white = add_multiband_white_noise(
    signal,
    sr,
    SNR_DB
)

babble = add_babble_noise(
    signal,
    sr,
    SNR_DB
)

dropouts = add_dropouts(
    signal,
    sr
)

# СОХРАНЕНИЕ

sf.write(
    f"{OUTPUT_DIR}/pink_noise.wav",
    pink,
    sr
)

sf.write(
    f"{OUTPUT_DIR}/white_noise.wav",
    white,
    sr
)

sf.write(
    f"{OUTPUT_DIR}/babble_noise.wav",
    babble,
    sr
)

sf.write(
    f"{OUTPUT_DIR}/dropouts.wav",
    dropouts,
    sr
)